export const SIGNIN = 'SIGN_IN'
export const SIGNOUT = 'SIGN_OUT'
export const STREAM_CREATE = 'STREAM_CREATE'
export const STREAM_EDIT = 'STREAM_EDIT'
export const STREAM_DELETE = 'STREAM_DELETE'
export const STREAMS_LIST = 'STREAMS_LIST'
export const STREAM_SHOW = 'STREAM_SHOW'